######################################################################
# Automatically generated by qmake (2.01a) lun. juin 14 11:17:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += fault.h Fault.hh launcher.hh log_creator.hh observer.hh
SOURCES += Fault.cpp launcher.cpp log_creator.cpp main.cpp observer.cpp
